# docker-compose -p webapp up --build

version: '3.4'

services:

    nginx:
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.docker/nginx/sites/:/etc/nginx/sites-available
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"

    php:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www/html
        depends_on:
            - database

    database:
        image: dockette/postgres:10
        env_file:
            - .env
        volumes:
            - database_data:/var/lib/postgresql/data

    adminer:
        image: dockette/adminer:dg
        ports:
            - "8082:80"

volumes:
  database_data:
    driver: local
